name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: antechamber-console
      - uses: actions/checkout@v4
        with:
          repository: jacogrande/antechamber-client
          path: antechamber-client
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
        working-directory: antechamber-console
      - run: bun run lint
        working-directory: antechamber-console
      - run: bun run build
        working-directory: antechamber-console
      - run: bun run test
        working-directory: antechamber-console
